name: Build & deploy

on:
  push:
    branches:
      - gh-release
  pull_request:
    branches:
      - gh-release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: unset ci
      run: unset CI
    
    - name: Install NPM packages
      run: npm i
    
    - name: Build project
      run: npm run build
      env:
        REACT_APP_ADMIN: ${{ secrets.REACT_APP_ADMIN }}
        REACT_APP_USER: ${{ secrets.REACT_APP_USER }}
        REACT_APP_ROOT: ${{ secrets.REACT_APP_ROOT }}
    
    

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./client/build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/gh-release'
   
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build